version: 0.2

#run-as: Linux-user-name

env:
#  shell: shell-tag
  variables:
    SONATYPE_USERNAME: "ida-operations"
#    key: "value"
#  parameter-store:
#    MAVEN_CENTRAL_SIGNING_KEY: "wynne-codepipeline-spike-maven-central-signing-key"
#    key: "value"
#  exported-variables:
#    - variable
#    - variable
  secrets-manager:
    SONATYPE_PASSWORD: "sonatype-password:password"
    MAVEN_CENTRAL_SIGNING_BASE64_KEY: "maven-central-signing:base64_key"
    MAVEN_CENTRAL_SIGNING_KEY_PASSWORD: "maven-central-signing:password"

#    key: secret-id:json-key:version-stage:version-id
  git-credential-helper: yes

#proxy:
#  upload-artifacts: no | yes
#  logs: no | yes

#batch:
#  fast-fail: false | true
#    # build-list:
#    # build-matrix:
#    # build-graph:

phases:
  install:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
#    runtime-versions:
#      runtime: version
#      runtime: version
    commands:
      - apt-get update
      - apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - aws --version
      - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      - apt-get update
      - apt-get install -y docker-ce docker-ce-cli containerd.io
      - dockerd &
#      - command
#    finally:
#      - command
#      - command
  pre_build:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
    commands:
      - ls -al
      - ls -al ../
      - aws s3 cp s3://wynne-codepipeline-spike/verify-dev-pki-version.txt ./verify-dev-pki-version.txt
      - MAVEN_CENTRAL_SIGNING_KEY=$(echo $MAVEN_CENTRAL_SIGNING_BASE64_KEY | base64 -d)
      - export MAVEN_CENTRAL_SIGNING_KEY
#      - ls -al
#      - pwd
#      - git rev-parse --show-toplevel
#      - cat .git/committer > ./last-committer
#      - command
#    finally:
#      - command
#      - command
  build:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
    commands:
      - BUILD_NUMBER=$(cat verify-dev-pki-version.txt) ./gradlew clean build publishToSonatype --stacktrace # closeAndReleaseSonatypeStagingRepository
      - echo $(( $(cat verify-dev-pki-version.txt) + 1)) > verify-dev-pki-version.txt
      - aws s3 cp verify-dev-pki-version.txt s3://wynne-codepipeline-spike/verify-dev-pki-version.txt
      - git tag "build_$(cat verify-dev-pki-version.txt)"
      - git push origin "build_$(cat verify-dev-pki-version.txt)"
      - cd ../verify-visual-regression-tests
      - docker build -t wynne-codepipeline-spike .

  #    finally:
#      - command
#      - command
  post_build:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
    commands:
      - docker tag wynne-codepipeline-spike:latest public.ecr.aws/f1g2b6b7/wynne-codepipeline-spike:latest
      - docker login -u AWS -p $(aws ecr-public get-login-password --region eu-west-2) public.ecr.aws/f1g2b6b7
      - docker push public.ecr.aws/f1g2b6b7/wynne-codepipeline-spike:latest
#    finally:
#      - command
#      - command
#reports:
#  report-group-name-or-arn:
#    files:
#      - location
#      - location
#    base-directory: location
#    discard-paths: no | yes
#    file-format: report-format
#artifacts:
#  files:
#    - location
#    - location
#  name: artifact-name
#  discard-paths: no | yes
#  base-directory: location
#  exclude-paths: excluded paths
#  enable-symlinks: no | yes
#  s3-prefix: prefix
#  secondary-artifacts:
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      name: secondary-artifact-name
#      discard-paths: no | yes
#      base-directory: location
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      discard-paths: no | yes
#      base-directory: location
#cache:
#  paths:
#    - path
#    - path
